### ISSUE TITLE
NMS Configuration - LibreNMS

### ISSUE THREAD

**Issue by aolsonesxtech** [CraftComputing/ProjectAxeEffect#13]
I was able to add a custom OS and discovery to get both temperature and humidity to librenms

2 files are needed. 1 in %librenms_directory%/includes/definitions/axeeffect.yaml
```
os: axeeffect
text: 'AxeEffect Environmental Probe'
type: environment
icon: generic
over:
    - { graph: device_temperature, text: Temperature }
    - { graph: device_humidity, text: Humidity }
    - { graph: device_ping_perf, text: 'ICMP Response' }
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.26381
discovery_modules:
    ports: false
    ports-stack: false
    entity-physical: false
    processors: false
    mempools: false
    cisco-vrf-lite: false
    storage: false
    hr-device: false
    discovery-protocols: false
    bgp-peers: false
    vlans: false
    ucd-diskio: false
    services: false
    stp: false
    ntp: false
    wireless: false
    fdb-table: false
poller_modules:
    ipmi: false
    entity-physical: false
    processors: false
    mempools: false
    storage: false
    netstats: false
    hr-mib: false
    ucd-mib: false
    ipSystemStats: false
    ports: false
    bgp-peers: false
    ospf: false
    ucd-diskio: false
    services: false
    stp: false
    ntp: false
    wireless: false
    fdb-table: false
    applications: false
``` 

and in %librenms_directory%/includes/definitions/discovery/axeeffect.yaml
```
mib: ENTITY-SENSOR-MIB
modules:
    sensors:
        temperature:
            data:
                -
                    oid:  entPhySensorTable
                    value: entPhySensorValue
                    divisor: 100
                    num_oid: '.1.3.6.1.2.1.99.1.1.1.4.0.{{ $index }}'
                    descr: 'Temperature'
                    index: 'entPhySensorValue.{{ $index }}'
        humidity:
            data:
                -
                    oid:  entPhySensorTable
                    value: entPhySensorValue
                    descr: 'Humidity'
                    divisor: 1000
                    num_oid: '.1.3.6.1.2.1.99.1.1.2.4.0'
```
if/when the final one comes out with more sensors, we may have to modify the naming here to specify which probe is which.
